### ISSUE TITLE
Make the resource Package[libvirt] optional

### ISSUE THREAD

**Issue by bjvrielink** [tux-o-matic/puppet-vkick#3]
As it is right now, one cannot use both this module and thias/libvirt at the same time, as they both are hard coded to manage a resource named Package[libvirt]

```puppet
Error: Duplicate declaration: Package[libvirt] is already declared in file /etc/puppet/environments/production/modules/libvirt/manifests/init.pp:68; cannot redeclare at /etc/puppet/environments/production/modules/vkick/manifests/host.pp:25
```

To manage the hypervisor, I already use thias/libvirt (to setup the network config, mainly). I only need guest.pp from the vkick module, but it requires host.pp. Either make this require optional, or make the Package resource optional.

**Comment by tux-o-matic** [comment]
On the host class you can now specify manage_libvirt_package => false to freely manage the libvirt package.
Will make a new release on Forge later.

**Comment by bjvrielink** [comment]
Please also do the same for the Service...
